services:
  - type: web
    name: product-jpa
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8083
      - key: SPRING_PROFILES_ACTIVE
        value: render
    healthCheckPath: /
    autoDeploy: true
