spring.datasource.url=${DB_URL:jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}}
spring.datasource.username=${DB_USERNAME:${PGUSER}}
spring.datasource.password=${DB_PASSWORD:${PGPASSWORD}}
spring.datasource.driver-class-name=org.postgresql.Driver
